name: SonarCloud.io

on:
  push:
    branches: [master, develop, feature/*]



jobs:
  scan:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # set the fetch-depth for actions/checkout to be sure you retrieve all commits to look for the semver commit message.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Add sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner --version 4.10.0

      - name: Scan
        run: |
          dotnet sonarscanner begin /k:"m4cx_OctoPatch" /o:"m4cx-github" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build OctoPatch.sln
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
